name: Docker Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Building
      uses: actions/checkout@v3
      
    - name: Running
      uses: wshihadeh/docker-deployment-action@v2
      with:
        remote_docker_host: root@gihub.com
