name: Docker Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: wshihadeh/docker-deployment-action@v2
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hnh-map

    - name: Running the Docker image
      run: docker run -d --restart=always -v /srv/hnh-map:/map -p 80:8080 --name map hnh-map
