name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      run: docker build -t map https://github.com/Cediner/hnh-map-vuetify.git
    - name: Run
      run: docker run -v /srv/hnh-map:/map -p 80:8080 map
