name: Docker Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Building
      uses: actions/checkout@v3
      
    - name: Running
      uses: addnab/docker-run-action@v3
      with:
        image: Cediner/hnh-map-vuetify:latest
        options: -v ${{ github.workspace }}:/var/www
        run: /
          composer install
          npm install
          npm run priduction
